/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('consultation').del();
  // Reset identity column back to 0
  //await knex.raw('DBCC CHECKIDENT("consultation", RESEED, 0)');
  await knex('consultation').insert([
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Accepted',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-12-11',
      start_time: '17:00:00',
      end_time: '18:00:00',
      type: 'offline',
      pathology: 'Headache',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'New',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-13',
      start_time: '12:00:00',
      end_time: '13:00:00',
      type: 'online',
      pathology: 'Back Pain',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Accepted',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-13',
      start_time: '10:00:00',
      end_time: '11:00:00',
      type: 'offline',
      pathology: 'Hypertension',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Done',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-16',
      start_time: '05:00:00',
      end_time: '06:00:00',
      type: 'online',
      pathology: 'Cardio D',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'New',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-16',
      start_time: '11:00:00',
      end_time: '12:00:00',
      type: 'offline',
      pathology: 'Diabetes',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Accepted',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-15',
      start_time: '05:00:00',
      end_time: '06:00:00',
      type: 'online',
      pathology: 'Common Cold',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Done',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-16',
      start_time: '05:00:00',
      end_time: '06:00:00',
      type: 'offline',
      pathology: 'Pneumonia',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Accepted',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-27',
      start_time: '17:00:00',
      end_time: '18:00:00',
      type: 'online',
      pathology: 'Allergy',
    },
    {
      patient_id: 4,
      doctor_id: 2,
      status: 'Done',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-27',
      start_time: '12:00:00',
      end_time: '13:00:00',
      type: 'offline',
      pathology: 'Diabetes',
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: 'Done',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-27',
      start_time: '12:00:00',
      end_time: '13:00:00',
      type: 'online',
      pathology: 'Headache',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Accepted',
      consultation_result: '',
      reason: 'Follow-up consultation for recurring headaches',
      date: '2024-12-08',
      start_time: '10:00:00',
      end_time: '11:00:00',
      type: 'offline',
      pathology: 'Headache',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'New',
      consultation_result: '',
      reason: 'Initial consultation for back pain',
      date: '2024-12-09',
      start_time: '11:00:00',
      end_time: '12:00:00',
      type: 'online',
      pathology: 'Back Pain',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Done',
      consultation_result: '',
      reason: 'Routine check-up and medication adjustment',
      date: '2024-12-10',
      start_time: '13:00:00',
      end_time: '14:00:00',
      type: 'offline',
      pathology: 'Hypertension',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Accepted',
      consultation_result: '',
      reason: 'Skin irritation and potential allergy review',
      date: '2024-12-11',
      start_time: '15:00:00',
      end_time: '16:00:00',
      type: 'online',
      pathology: 'Common Cold',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'New',
      consultation_result: '',
      reason: 'Pre-surgery evaluation for minor operation',
      date: '2024-12-12',
      start_time: '16:00:00',
      end_time: '17:00:00',
      type: 'offline',
      pathology: 'Diabetes',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Done',
      consultation_result: '',
      reason: 'Headache follow-up',
      date: '2024-12-13',
      start_time: '09:00:00',
      end_time: '10:00:00',
      type: 'online',
      pathology: 'Headache',
    },
    {
      patient_id: 4,
      doctor_id: 2,
      status: 'Accepted',
      consultation_result: '',
      reason: 'Diabetes management plan review',
      date: '2024-12-08',
      start_time: '17:00:00',
      end_time: '18:00:00',
      type: 'offline',
      pathology: 'Diabetes',
    },
    {
      patient_id: 4,
      doctor_id: 2,
      status: 'New',
      consultation_result: '',
      reason: 'Discussion of Pneumonia medication options',
      date: '2024-12-15',
      start_time: '14:00:00',
      end_time: '15:00:00',
      type: 'online',
      pathology: 'Pneumonia',
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: 'Accepted',
      consultation_result: '',
      reason: 'Consultation for persistent Headaches',
      date: '2024-12-16',
      start_time: '10:00:00',
      end_time: '11:00:00',
      type: 'offline',
      pathology: 'Headache',
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: 'Done',
      consultation_result: '',
      reason: 'Physical therapy plan for Back Pain',
      date: '2024-12-17',
      start_time: '13:00:00',
      end_time: '14:00:00',
      type: 'online',
      pathology: 'Back Pain',
    },
    // Tháng 1
    {
      patient_id: 1,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for chronic back pain",
      date: "2024-01-02",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Back Pain"
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for cardio issues",
      date: "2024-01-05",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "online",
      pathology: "Cardio D"
    },
    {
      patient_id: 1,
      doctor_id: 5,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for common cold symptoms",
      date: "2024-01-10",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "offline",
      pathology: "Common Cold"
    },
    {
      patient_id: 4,
      doctor_id: 6,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diabetes management",
      date: "2024-01-15",
      start_time: "11:00:00",
      end_time: "12:00:00",
      type: "online",
      pathology: "Diabetes"
    },
    {
      patient_id: 1,
      doctor_id: 7,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diarrhea issues",
      date: "2024-01-20",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Diarrhea"
    },
    //Tháng 2
    {
      patient_id: 4,
      doctor_id: 8,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for gastritis",
      date: "2024-02-02",
      start_time: "15:00:00",
      end_time: "16:00:00",
      type: "online",
      pathology: "Gastritis"
    },
    {
      patient_id: 1,
      doctor_id: 9,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for recurrent headaches",
      date: "2024-02-05",
      start_time: "13:00:00",
      end_time: "14:00:00",
      type: "offline",
      pathology: "Headache"
    },
    {
      patient_id: 4,
      doctor_id: 10,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hepatitis",
      date: "2024-02-10",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "online",
      pathology: "Hepatitis"
    },
    {
      patient_id: 1,
      doctor_id: 11,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hypertension",
      date: "2024-02-12",
      start_time: "11:00:00",
      end_time: "12:00:00",
      type: "offline",
      pathology: "Hypertension"
    },
    {
      patient_id: 4,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for pneumonia symptoms",
      date: "2024-02-18",
      start_time: "09:00:00",
      end_time: "10:00:00",
      type: "online",
      pathology: "Pneumonia"
    },
    // Tháng 3
    {
      patient_id: 1,
      doctor_id: 3,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for cardio issues",
      date: "2024-03-01",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Cardio D"
    },
    {
      patient_id: 4,
      doctor_id: 5,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for common cold symptoms",
      date: "2024-03-05",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "online",
      pathology: "Common Cold"
    },
    {
      patient_id: 1,
      doctor_id: 6,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diabetes management",
      date: "2024-03-08",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "offline",
      pathology: "Diabetes"
    },
    {
      patient_id: 4,
      doctor_id: 7,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diarrhea issues",
      date: "2024-03-12",
      start_time: "11:00:00",
      end_time: "12:00:00",
      type: "online",
      pathology: "Diarrhea"
    },
    {
      patient_id: 1,
      doctor_id: 8,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for gastritis",
      date: "2024-03-15",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Gastritis"
    },
    // Tháng 4
    {
      patient_id: 4,
      doctor_id: 9,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for recurrent headaches",
      date: "2024-04-02",
      start_time: "15:00:00",
      end_time: "16:00:00",
      type: "online",
      pathology: "Headache"
    },
    {
      patient_id: 1,
      doctor_id: 10,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hepatitis",
      date: "2024-04-05",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "offline",
      pathology: "Hepatitis"
    },
    {
      patient_id: 4,
      doctor_id: 11,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hypertension",
      date: "2024-04-10",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "online",
      pathology: "Hypertension"
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for pneumonia symptoms",
      date: "2024-04-12",
      start_time: "09:00:00",
      end_time: "10:00:00",
      type: "offline",
      pathology: "Pneumonia"
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for cardio issues",
      date: "2024-04-20",
      start_time: "13:00:00",
      end_time: "14:00:00",
      type: "online",
      pathology: "Cardio D"
    },
    // Tháng 5
    {
      patient_id: 1,
      doctor_id: 5,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for common cold symptoms",
      date: "2024-05-01",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Common Cold"
    },
    {
      patient_id: 4,
      doctor_id: 6,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diabetes management",
      date: "2024-05-05",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "online",
      pathology: "Diabetes"
    },
    {
      patient_id: 1,
      doctor_id: 7,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diarrhea issues",
      date: "2024-05-08",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "offline",
      pathology: "Diarrhea"
    },
    {
      patient_id: 4,
      doctor_id: 8,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for gastritis",
      date: "2024-05-12",
      start_time: "11:00:00",
      end_time: "12:00:00",
      type: "online",
      pathology: "Gastritis"
    },
    {
      patient_id: 1,
      doctor_id: 9,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for recurrent headaches",
      date: "2024-05-15",
      start_time: "13:00:00",
      end_time: "14:00:00",
      type: "offline",
      pathology: "Headache"
    },
    // Tháng 6
    {
      patient_id: 4,
      doctor_id: 10,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hepatitis",
      date: "2024-06-02",
      start_time: "15:00:00",
      end_time: "16:00:00",
      type: "online",
      pathology: "Hepatitis"
    },
    {
      patient_id: 1,
      doctor_id: 11,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hypertension",
      date: "2024-06-05",
      start_time: "13:00:00",
      end_time: "14:00:00",
      type: "offline",
      pathology: "Hypertension"
    },
    {
      patient_id: 4,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for pneumonia symptoms",
      date: "2024-06-10",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "online",
      pathology: "Pneumonia"
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for cardio issues",
      date: "2024-06-12",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "offline",
      pathology: "Cardio D"
    },
    {
      patient_id: 4,
      doctor_id: 5,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for common cold symptoms",
      date: "2024-06-15",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "online",
      pathology: "Common Cold"
    },
    // Tháng 7
    {
      patient_id: 1,
      doctor_id: 6,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diabetes management",
      date: "2024-07-02",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Diabetes"
    },
    {
      patient_id: 4,
      doctor_id: 7,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diarrhea issues",
      date: "2024-07-05",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "online",
      pathology: "Diarrhea"
    },
    {
      patient_id: 1,
      doctor_id: 8,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for gastritis",
      date: "2024-07-10",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "offline",
      pathology: "Gastritis"
    },
    {
      patient_id: 4,
      doctor_id: 9,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for recurrent headaches",
      date: "2024-07-15",
      start_time: "11:00:00",
      end_time: "12:00:00",
      type: "online",
      pathology: "Headache"
    },
    {
      patient_id: 1,
      doctor_id: 10,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hepatitis",
      date: "2024-07-18",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Hepatitis"
    },
    // Tháng 8
    {
      patient_id: 4,
      doctor_id: 11,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hypertension",
      date: "2024-08-02",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "online",
      pathology: "Hypertension"
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for pneumonia symptoms",
      date: "2024-08-05",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "offline",
      pathology: "Pneumonia"
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for cardio issues",
      date: "2024-08-10",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "online",
      pathology: "Cardio D"
    },
    {
      patient_id: 1,
      doctor_id: 5,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for common cold symptoms",
      date: "2024-08-15",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "offline",
      pathology: "Common Cold"
    },
    {
      patient_id: 4,
      doctor_id: 6,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diabetes management",
      date: "2024-08-18",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "online",
      pathology: "Diabetes"
    },
    // Tháng 9
    {
      patient_id: 1,
      doctor_id: 7,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diarrhea issues",
      date: "2024-09-02",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Diarrhea"
    },
    {
      patient_id: 4,
      doctor_id: 8,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for gastritis",
      date: "2024-09-05",
      start_time: "13:00:00",
      end_time: "14:00:00",
      type: "online",
      pathology: "Gastritis"
    },
    {
      patient_id: 1,
      doctor_id: 9,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for recurrent headaches",
      date: "2024-09-10",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "offline",
      pathology: "Headache"
    },
    {
      patient_id: 4,
      doctor_id: 10,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hepatitis",
      date: "2024-09-12",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "online",
      pathology: "Hepatitis"
    },
    {
      patient_id: 1,
      doctor_id: 11,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hypertension",
      date: "2024-09-15",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Hypertension"
    },
    // Tháng 10
    {
      patient_id: 1,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for chronic back pain",
      date: "2024-10-05",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Back Pain"
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for cardio issues",
      date: "2024-10-07",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "online",
      pathology: "Cardio D"
    },
    {
      patient_id: 1,
      doctor_id: 5,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for common cold symptoms",
      date: "2024-10-12",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "offline",
      pathology: "Common Cold"
    },
    {
      patient_id: 4,
      doctor_id: 6,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diabetes management",
      date: "2024-10-14",
      start_time: "11:00:00",
      end_time: "12:00:00",
      type: "online",
      pathology: "Diabetes"
    },
    {
      patient_id: 1,
      doctor_id: 7,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diarrhea issues",
      date: "2024-10-20",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Diarrhea"
    },
    // Tháng 11
    {
      patient_id: 4,
      doctor_id: 8,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for gastritis",
      date: "2024-11-02",
      start_time: "15:00:00",
      end_time: "16:00:00",
      type: "online",
      pathology: "Gastritis"
    },
    {
      patient_id: 1,
      doctor_id: 9,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for recurrent headaches",
      date: "2024-11-05",
      start_time: "13:00:00",
      end_time: "14:00:00",
      type: "offline",
      pathology: "Headache"
    },
    {
      patient_id: 4,
      doctor_id: 10,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hepatitis",
      date: "2024-11-10",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "online",
      pathology: "Hepatitis"
    },
    {
      patient_id: 1,
      doctor_id: 11,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for hypertension",
      date: "2024-11-12",
      start_time: "11:00:00",
      end_time: "12:00:00",
      type: "offline",
      pathology: "Hypertension"
    },
    {
      patient_id: 4,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for pneumonia symptoms",
      date: "2024-11-18",
      start_time: "09:00:00",
      end_time: "10:00:00",
      type: "online",
      pathology: "Pneumonia"
    },
    // tháng 12
    {
      patient_id: 1,
      doctor_id: 3,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for cardio issues",
      date: "2024-12-02",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Cardio D"
    },
    {
      patient_id: 4,
      doctor_id: 5,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for common cold symptoms",
      date: "2024-12-05",
      start_time: "12:00:00",
      end_time: "13:00:00",
      type: "online",
      pathology: "Common Cold"
    },
    {
      patient_id: 1,
      doctor_id: 6,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diabetes management",
      date: "2024-12-08",
      start_time: "14:00:00",
      end_time: "15:00:00",
      type: "offline",
      pathology: "Diabetes"
    },
    {
      patient_id: 4,
      doctor_id: 7,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for diarrhea issues",
      date: "2024-12-12",
      start_time: "11:00:00",
      end_time: "12:00:00",
      type: "online",
      pathology: "Diarrhea"
    },
    {
      patient_id: 1,
      doctor_id: 8,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for gastritis",
      date: "2024-12-15",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Gastritis"
    },
    {
      patient_id: 13,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for headache",
      date: "2025-01-06",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Headache"
    },
    {
      patient_id: 14,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for cold",
      date: "2025-01-06",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Cardio D"
    },
    {
      patient_id: 15,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for back pain",
      date: "2025-01-06",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Back Pain"
    },
    {
      patient_id: 16,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for stomach",
      date: "2025-01-06",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Diarrhea"
    },
    {
      patient_id: 17,
      doctor_id: 2,
      status: "Done",
      consultation_result: "",
      reason: "Consultation for spinal Degeneration",
      date: "2025-01-06",
      start_time: "10:00:00",
      end_time: "11:00:00",
      type: "offline",
      pathology: "Back Pain"
    }
  ]);
};