/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('consultation').del();
  // Reset identity column back to 0
  //await knex.raw('DBCC CHECKIDENT("consultation", RESEED, 0)');
  await knex('consultation').insert([
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Accepted',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-12-11',
      start_time: '17:00:00',
      end_time: '18:00:00',
      type: 'offline',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'New',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-13',
      start_time: '12:00:00',
      end_time: '13:00:00',
      type: 'online',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Accepted',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-13',
      start_time: '10:00:00',
      end_time: '11:00:00',
      type: 'offline',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Done',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-16',
      start_time: '05:00:00',
      end_time: '06:00:00',
      type: 'online',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'New',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-16',
      start_time: '11:00:00',
      end_time: '12:00:00',
      type: 'offline',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Accepted',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-15',
      start_time: '05:00:00',
      end_time: '06:00:00',
      type: 'online',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Done',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-16',
      start_time: '05:00:00',
      end_time: '06:00:00',
      type: 'offline',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Accepted',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-27',
      start_time: '17:00:00',
      end_time: '18:00:00',
      type: 'online',
    },
    {
      patient_id: 4,
      doctor_id: 2,
      status: 'Done',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-27',
      start_time: '12:00:00',
      end_time: '13:00:00',
      type: 'offline',
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: 'Done',
      consultation_result: '',
      reason: 'kkkkkkkk',
      date: '2024-11-27',
      start_time: '12:00:00',
      end_time: '13:00:00',
      type: 'online',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Accepted',
      consultation_result: '',
      reason: 'Follow-up consultation for recurring headaches',
      date: '2024-12-08',
      start_time: '10:00:00',
      end_time: '11:00:00',
      type: 'offline',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'New',
      consultation_result: '',
      reason: 'Initial consultation for back pain',
      date: '2024-12-09',
      start_time: '11:00:00',
      end_time: '12:00:00',
      type: 'online',
    },
    {
      patient_id: 1,
      doctor_id: 2,
      status: 'Done',
      consultation_result: '',
      reason: 'Routine check-up and medication adjustment',
      date: '2024-12-10',
      start_time: '13:00:00',
      end_time: '14:00:00',
      type: 'offline',
    },

    // Patient 1 with Doctor 3
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Accepted',
      consultation_result: '',
      reason: 'Skin irritation and potential allergy review',
      date: '2024-12-11',
      start_time: '15:00:00',
      end_time: '16:00:00',
      type: 'online',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'New',
      consultation_result: '',
      reason: 'Pre-surgery evaluation for minor operation',
      date: '2024-12-12',
      start_time: '16:00:00',
      end_time: '17:00:00',
      type: 'offline',
    },
    {
      patient_id: 1,
      doctor_id: 3,
      status: 'Done',
      consultation_result: '',
      reason: 'Post-surgery follow-up',
      date: '2024-12-13',
      start_time: '09:00:00',
      end_time: '10:00:00',
      type: 'online',
    },

    // Patient 4 with Doctor 2
    {
      patient_id: 4,
      doctor_id: 2,
      status: 'Accepted',
      consultation_result: '',
      reason: 'Diabetes management plan review',
      date: '2024-12-08',
      start_time: '17:00:00',
      end_time: '18:00:00',
      type: 'offline',
    },
    {
      patient_id: 4,
      doctor_id: 2,
      status: 'New',
      consultation_result: '',
      reason: 'Discussion of cholesterol medication options',
      date: '2024-12-15',
      start_time: '14:00:00',
      end_time: '15:00:00',
      type: 'online',
    },

    // Patient 4 with Doctor 3
    {
      patient_id: 4,
      doctor_id: 3,
      status: 'Accepted',
      consultation_result: '',
      reason: 'Consultation for persistent migraines',
      date: '2024-12-16',
      start_time: '10:00:00',
      end_time: '11:00:00',
      type: 'offline',
    },
    {
      patient_id: 4,
      doctor_id: 3,
      status: 'Done',
      consultation_result: '',
      reason: 'Physical therapy plan for joint pain',
      date: '2024-12-17',
      start_time: '13:00:00',
      end_time: '14:00:00',
      type: 'online',
    },
  ]);
};
